---
- name: "copy backend file"
  become: true
  copy:
    src: /root/project/backend
    dest: /root
    force: no

- name: "Start App"
  become: true
  shell: |
    npm install
    pm2 stop default
    pm2 start npm -- start